/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebSitesiRouteImport } from './routes/web-sitesi'
import { Route as UctanUcaYazilimRouteImport } from './routes/uctan-uca-yazilim'
import { Route as SifreSifirlaRouteImport } from './routes/sifre-sifirla'
import { Route as PuslaRouteImport } from './routes/pusla'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as OtomasyonRouteImport } from './routes/otomasyon'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as KarHesaplayiciRouteImport } from './routes/kar-hesaplayici'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HepsiburadaKarHesaplayiciRouteImport } from './routes/hepsiburada-kar-hesaplayici'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppPuslaRouteImport } from './routes/app.pusla'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppPuslaIndexRouteImport } from './routes/app.pusla.index'
import { Route as AppPuslaStokRouteImport } from './routes/app.pusla.stok'
import { Route as AppPuslaSatislarRouteImport } from './routes/app.pusla.satislar'
import { Route as AppPuslaReklamRouteImport } from './routes/app.pusla.reklam'
import { Route as AppPuslaRaporlarRouteImport } from './routes/app.pusla.raporlar'
import { Route as AppPuslaIadelerRouteImport } from './routes/app.pusla.iadeler'
import { Route as AppPuslaHatirlaticilarRouteImport } from './routes/app.pusla.hatirlaticilar'
import { Route as AppPuslaGiderlerRouteImport } from './routes/app.pusla.giderler'
import { Route as AppPuslaCarilerRouteImport } from './routes/app.pusla.cariler'
import { Route as AppPuslaAyarlarRouteImport } from './routes/app.pusla.ayarlar'
import { Route as AppPuslaAlislarRouteImport } from './routes/app.pusla.alislar'
import { Route as AppPuslaReklamIndexRouteImport } from './routes/app.pusla.reklam.index'
import { Route as AppPuslaReklamIdRouteImport } from './routes/app.pusla.reklam.$id'

const WebSitesiRoute = WebSitesiRouteImport.update({
  id: '/web-sitesi',
  path: '/web-sitesi',
  getParentRoute: () => rootRouteImport,
} as any)
const UctanUcaYazilimRoute = UctanUcaYazilimRouteImport.update({
  id: '/uctan-uca-yazilim',
  path: '/uctan-uca-yazilim',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreSifirlaRoute = SifreSifirlaRouteImport.update({
  id: '/sifre-sifirla',
  path: '/sifre-sifirla',
  getParentRoute: () => rootRouteImport,
} as any)
const PuslaRoute = PuslaRouteImport.update({
  id: '/pusla',
  path: '/pusla',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomasyonRoute = OtomasyonRouteImport.update({
  id: '/otomasyon',
  path: '/otomasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const KarHesaplayiciRoute = KarHesaplayiciRouteImport.update({
  id: '/kar-hesaplayici',
  path: '/kar-hesaplayici',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HepsiburadaKarHesaplayiciRoute =
  HepsiburadaKarHesaplayiciRouteImport.update({
    id: '/hepsiburada-kar-hesaplayici',
    path: '/hepsiburada-kar-hesaplayici',
    getParentRoute: () => rootRouteImport,
  } as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppPuslaRoute = AppPuslaRouteImport.update({
  id: '/app/pusla',
  path: '/app/pusla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppPuslaIndexRoute = AppPuslaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaStokRoute = AppPuslaStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaSatislarRoute = AppPuslaSatislarRouteImport.update({
  id: '/satislar',
  path: '/satislar',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaReklamRoute = AppPuslaReklamRouteImport.update({
  id: '/reklam',
  path: '/reklam',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaRaporlarRoute = AppPuslaRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaIadelerRoute = AppPuslaIadelerRouteImport.update({
  id: '/iadeler',
  path: '/iadeler',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaHatirlaticilarRoute = AppPuslaHatirlaticilarRouteImport.update({
  id: '/hatirlaticilar',
  path: '/hatirlaticilar',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaGiderlerRoute = AppPuslaGiderlerRouteImport.update({
  id: '/giderler',
  path: '/giderler',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaCarilerRoute = AppPuslaCarilerRouteImport.update({
  id: '/cariler',
  path: '/cariler',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaAyarlarRoute = AppPuslaAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaAlislarRoute = AppPuslaAlislarRouteImport.update({
  id: '/alislar',
  path: '/alislar',
  getParentRoute: () => AppPuslaRoute,
} as any)
const AppPuslaReklamIndexRoute = AppPuslaReklamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPuslaReklamRoute,
} as any)
const AppPuslaReklamIdRoute = AppPuslaReklamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPuslaReklamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/hakkimizda': typeof HakkimizdaRoute
  '/hepsiburada-kar-hesaplayici': typeof HepsiburadaKarHesaplayiciRoute
  '/iletisim': typeof IletisimRoute
  '/kar-hesaplayici': typeof KarHesaplayiciRoute
  '/odeme': typeof OdemeRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/pusla': typeof PuslaRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/uctan-uca-yazilim': typeof UctanUcaYazilimRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/pusla': typeof AppPuslaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/app/pusla/alislar': typeof AppPuslaAlislarRoute
  '/app/pusla/ayarlar': typeof AppPuslaAyarlarRoute
  '/app/pusla/cariler': typeof AppPuslaCarilerRoute
  '/app/pusla/giderler': typeof AppPuslaGiderlerRoute
  '/app/pusla/hatirlaticilar': typeof AppPuslaHatirlaticilarRoute
  '/app/pusla/iadeler': typeof AppPuslaIadelerRoute
  '/app/pusla/raporlar': typeof AppPuslaRaporlarRoute
  '/app/pusla/reklam': typeof AppPuslaReklamRouteWithChildren
  '/app/pusla/satislar': typeof AppPuslaSatislarRoute
  '/app/pusla/stok': typeof AppPuslaStokRoute
  '/app/pusla/': typeof AppPuslaIndexRoute
  '/app/pusla/reklam/$id': typeof AppPuslaReklamIdRoute
  '/app/pusla/reklam/': typeof AppPuslaReklamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hepsiburada-kar-hesaplayici': typeof HepsiburadaKarHesaplayiciRoute
  '/iletisim': typeof IletisimRoute
  '/kar-hesaplayici': typeof KarHesaplayiciRoute
  '/odeme': typeof OdemeRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/pusla': typeof PuslaRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/uctan-uca-yazilim': typeof UctanUcaYazilimRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/app/pusla/alislar': typeof AppPuslaAlislarRoute
  '/app/pusla/ayarlar': typeof AppPuslaAyarlarRoute
  '/app/pusla/cariler': typeof AppPuslaCarilerRoute
  '/app/pusla/giderler': typeof AppPuslaGiderlerRoute
  '/app/pusla/hatirlaticilar': typeof AppPuslaHatirlaticilarRoute
  '/app/pusla/iadeler': typeof AppPuslaIadelerRoute
  '/app/pusla/raporlar': typeof AppPuslaRaporlarRoute
  '/app/pusla/satislar': typeof AppPuslaSatislarRoute
  '/app/pusla/stok': typeof AppPuslaStokRoute
  '/app/pusla': typeof AppPuslaIndexRoute
  '/app/pusla/reklam/$id': typeof AppPuslaReklamIdRoute
  '/app/pusla/reklam': typeof AppPuslaReklamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/hakkimizda': typeof HakkimizdaRoute
  '/hepsiburada-kar-hesaplayici': typeof HepsiburadaKarHesaplayiciRoute
  '/iletisim': typeof IletisimRoute
  '/kar-hesaplayici': typeof KarHesaplayiciRoute
  '/odeme': typeof OdemeRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/pusla': typeof PuslaRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/uctan-uca-yazilim': typeof UctanUcaYazilimRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/pusla': typeof AppPuslaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/app/pusla/alislar': typeof AppPuslaAlislarRoute
  '/app/pusla/ayarlar': typeof AppPuslaAyarlarRoute
  '/app/pusla/cariler': typeof AppPuslaCarilerRoute
  '/app/pusla/giderler': typeof AppPuslaGiderlerRoute
  '/app/pusla/hatirlaticilar': typeof AppPuslaHatirlaticilarRoute
  '/app/pusla/iadeler': typeof AppPuslaIadelerRoute
  '/app/pusla/raporlar': typeof AppPuslaRaporlarRoute
  '/app/pusla/reklam': typeof AppPuslaReklamRouteWithChildren
  '/app/pusla/satislar': typeof AppPuslaSatislarRoute
  '/app/pusla/stok': typeof AppPuslaStokRoute
  '/app/pusla/': typeof AppPuslaIndexRoute
  '/app/pusla/reklam/$id': typeof AppPuslaReklamIdRoute
  '/app/pusla/reklam/': typeof AppPuslaReklamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/hakkimizda'
    | '/hepsiburada-kar-hesaplayici'
    | '/iletisim'
    | '/kar-hesaplayici'
    | '/odeme'
    | '/otomasyon'
    | '/panel'
    | '/pusla'
    | '/sifre-sifirla'
    | '/uctan-uca-yazilim'
    | '/web-sitesi'
    | '/admin/users'
    | '/app/pusla'
    | '/blog/$slug'
    | '/blog/'
    | '/app/pusla/alislar'
    | '/app/pusla/ayarlar'
    | '/app/pusla/cariler'
    | '/app/pusla/giderler'
    | '/app/pusla/hatirlaticilar'
    | '/app/pusla/iadeler'
    | '/app/pusla/raporlar'
    | '/app/pusla/reklam'
    | '/app/pusla/satislar'
    | '/app/pusla/stok'
    | '/app/pusla/'
    | '/app/pusla/reklam/$id'
    | '/app/pusla/reklam/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/hakkimizda'
    | '/hepsiburada-kar-hesaplayici'
    | '/iletisim'
    | '/kar-hesaplayici'
    | '/odeme'
    | '/otomasyon'
    | '/panel'
    | '/pusla'
    | '/sifre-sifirla'
    | '/uctan-uca-yazilim'
    | '/web-sitesi'
    | '/admin/users'
    | '/blog/$slug'
    | '/blog'
    | '/app/pusla/alislar'
    | '/app/pusla/ayarlar'
    | '/app/pusla/cariler'
    | '/app/pusla/giderler'
    | '/app/pusla/hatirlaticilar'
    | '/app/pusla/iadeler'
    | '/app/pusla/raporlar'
    | '/app/pusla/satislar'
    | '/app/pusla/stok'
    | '/app/pusla'
    | '/app/pusla/reklam/$id'
    | '/app/pusla/reklam'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/hakkimizda'
    | '/hepsiburada-kar-hesaplayici'
    | '/iletisim'
    | '/kar-hesaplayici'
    | '/odeme'
    | '/otomasyon'
    | '/panel'
    | '/pusla'
    | '/sifre-sifirla'
    | '/uctan-uca-yazilim'
    | '/web-sitesi'
    | '/admin/users'
    | '/app/pusla'
    | '/blog/$slug'
    | '/blog/'
    | '/app/pusla/alislar'
    | '/app/pusla/ayarlar'
    | '/app/pusla/cariler'
    | '/app/pusla/giderler'
    | '/app/pusla/hatirlaticilar'
    | '/app/pusla/iadeler'
    | '/app/pusla/raporlar'
    | '/app/pusla/reklam'
    | '/app/pusla/satislar'
    | '/app/pusla/stok'
    | '/app/pusla/'
    | '/app/pusla/reklam/$id'
    | '/app/pusla/reklam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  HakkimizdaRoute: typeof HakkimizdaRoute
  HepsiburadaKarHesaplayiciRoute: typeof HepsiburadaKarHesaplayiciRoute
  IletisimRoute: typeof IletisimRoute
  KarHesaplayiciRoute: typeof KarHesaplayiciRoute
  OdemeRoute: typeof OdemeRoute
  OtomasyonRoute: typeof OtomasyonRoute
  PanelRoute: typeof PanelRoute
  PuslaRoute: typeof PuslaRoute
  SifreSifirlaRoute: typeof SifreSifirlaRoute
  UctanUcaYazilimRoute: typeof UctanUcaYazilimRoute
  WebSitesiRoute: typeof WebSitesiRoute
  AppPuslaRoute: typeof AppPuslaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-sitesi': {
      id: '/web-sitesi'
      path: '/web-sitesi'
      fullPath: '/web-sitesi'
      preLoaderRoute: typeof WebSitesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uctan-uca-yazilim': {
      id: '/uctan-uca-yazilim'
      path: '/uctan-uca-yazilim'
      fullPath: '/uctan-uca-yazilim'
      preLoaderRoute: typeof UctanUcaYazilimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-sifirla': {
      id: '/sifre-sifirla'
      path: '/sifre-sifirla'
      fullPath: '/sifre-sifirla'
      preLoaderRoute: typeof SifreSifirlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pusla': {
      id: '/pusla'
      path: '/pusla'
      fullPath: '/pusla'
      preLoaderRoute: typeof PuslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomasyon': {
      id: '/otomasyon'
      path: '/otomasyon'
      fullPath: '/otomasyon'
      preLoaderRoute: typeof OtomasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kar-hesaplayici': {
      id: '/kar-hesaplayici'
      path: '/kar-hesaplayici'
      fullPath: '/kar-hesaplayici'
      preLoaderRoute: typeof KarHesaplayiciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hepsiburada-kar-hesaplayici': {
      id: '/hepsiburada-kar-hesaplayici'
      path: '/hepsiburada-kar-hesaplayici'
      fullPath: '/hepsiburada-kar-hesaplayici'
      preLoaderRoute: typeof HepsiburadaKarHesaplayiciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/pusla': {
      id: '/app/pusla'
      path: '/app/pusla'
      fullPath: '/app/pusla'
      preLoaderRoute: typeof AppPuslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/pusla/': {
      id: '/app/pusla/'
      path: '/'
      fullPath: '/app/pusla/'
      preLoaderRoute: typeof AppPuslaIndexRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/stok': {
      id: '/app/pusla/stok'
      path: '/stok'
      fullPath: '/app/pusla/stok'
      preLoaderRoute: typeof AppPuslaStokRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/satislar': {
      id: '/app/pusla/satislar'
      path: '/satislar'
      fullPath: '/app/pusla/satislar'
      preLoaderRoute: typeof AppPuslaSatislarRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/reklam': {
      id: '/app/pusla/reklam'
      path: '/reklam'
      fullPath: '/app/pusla/reklam'
      preLoaderRoute: typeof AppPuslaReklamRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/raporlar': {
      id: '/app/pusla/raporlar'
      path: '/raporlar'
      fullPath: '/app/pusla/raporlar'
      preLoaderRoute: typeof AppPuslaRaporlarRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/iadeler': {
      id: '/app/pusla/iadeler'
      path: '/iadeler'
      fullPath: '/app/pusla/iadeler'
      preLoaderRoute: typeof AppPuslaIadelerRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/hatirlaticilar': {
      id: '/app/pusla/hatirlaticilar'
      path: '/hatirlaticilar'
      fullPath: '/app/pusla/hatirlaticilar'
      preLoaderRoute: typeof AppPuslaHatirlaticilarRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/giderler': {
      id: '/app/pusla/giderler'
      path: '/giderler'
      fullPath: '/app/pusla/giderler'
      preLoaderRoute: typeof AppPuslaGiderlerRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/cariler': {
      id: '/app/pusla/cariler'
      path: '/cariler'
      fullPath: '/app/pusla/cariler'
      preLoaderRoute: typeof AppPuslaCarilerRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/ayarlar': {
      id: '/app/pusla/ayarlar'
      path: '/ayarlar'
      fullPath: '/app/pusla/ayarlar'
      preLoaderRoute: typeof AppPuslaAyarlarRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/alislar': {
      id: '/app/pusla/alislar'
      path: '/alislar'
      fullPath: '/app/pusla/alislar'
      preLoaderRoute: typeof AppPuslaAlislarRouteImport
      parentRoute: typeof AppPuslaRoute
    }
    '/app/pusla/reklam/': {
      id: '/app/pusla/reklam/'
      path: '/'
      fullPath: '/app/pusla/reklam/'
      preLoaderRoute: typeof AppPuslaReklamIndexRouteImport
      parentRoute: typeof AppPuslaReklamRoute
    }
    '/app/pusla/reklam/$id': {
      id: '/app/pusla/reklam/$id'
      path: '/$id'
      fullPath: '/app/pusla/reklam/$id'
      preLoaderRoute: typeof AppPuslaReklamIdRouteImport
      parentRoute: typeof AppPuslaReklamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface AppPuslaReklamRouteChildren {
  AppPuslaReklamIdRoute: typeof AppPuslaReklamIdRoute
  AppPuslaReklamIndexRoute: typeof AppPuslaReklamIndexRoute
}

const AppPuslaReklamRouteChildren: AppPuslaReklamRouteChildren = {
  AppPuslaReklamIdRoute: AppPuslaReklamIdRoute,
  AppPuslaReklamIndexRoute: AppPuslaReklamIndexRoute,
}

const AppPuslaReklamRouteWithChildren = AppPuslaReklamRoute._addFileChildren(
  AppPuslaReklamRouteChildren,
)

interface AppPuslaRouteChildren {
  AppPuslaAlislarRoute: typeof AppPuslaAlislarRoute
  AppPuslaAyarlarRoute: typeof AppPuslaAyarlarRoute
  AppPuslaCarilerRoute: typeof AppPuslaCarilerRoute
  AppPuslaGiderlerRoute: typeof AppPuslaGiderlerRoute
  AppPuslaHatirlaticilarRoute: typeof AppPuslaHatirlaticilarRoute
  AppPuslaIadelerRoute: typeof AppPuslaIadelerRoute
  AppPuslaRaporlarRoute: typeof AppPuslaRaporlarRoute
  AppPuslaReklamRoute: typeof AppPuslaReklamRouteWithChildren
  AppPuslaSatislarRoute: typeof AppPuslaSatislarRoute
  AppPuslaStokRoute: typeof AppPuslaStokRoute
  AppPuslaIndexRoute: typeof AppPuslaIndexRoute
}

const AppPuslaRouteChildren: AppPuslaRouteChildren = {
  AppPuslaAlislarRoute: AppPuslaAlislarRoute,
  AppPuslaAyarlarRoute: AppPuslaAyarlarRoute,
  AppPuslaCarilerRoute: AppPuslaCarilerRoute,
  AppPuslaGiderlerRoute: AppPuslaGiderlerRoute,
  AppPuslaHatirlaticilarRoute: AppPuslaHatirlaticilarRoute,
  AppPuslaIadelerRoute: AppPuslaIadelerRoute,
  AppPuslaRaporlarRoute: AppPuslaRaporlarRoute,
  AppPuslaReklamRoute: AppPuslaReklamRouteWithChildren,
  AppPuslaSatislarRoute: AppPuslaSatislarRoute,
  AppPuslaStokRoute: AppPuslaStokRoute,
  AppPuslaIndexRoute: AppPuslaIndexRoute,
}

const AppPuslaRouteWithChildren = AppPuslaRoute._addFileChildren(
  AppPuslaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  HakkimizdaRoute: HakkimizdaRoute,
  HepsiburadaKarHesaplayiciRoute: HepsiburadaKarHesaplayiciRoute,
  IletisimRoute: IletisimRoute,
  KarHesaplayiciRoute: KarHesaplayiciRoute,
  OdemeRoute: OdemeRoute,
  OtomasyonRoute: OtomasyonRoute,
  PanelRoute: PanelRoute,
  PuslaRoute: PuslaRoute,
  SifreSifirlaRoute: SifreSifirlaRoute,
  UctanUcaYazilimRoute: UctanUcaYazilimRoute,
  WebSitesiRoute: WebSitesiRoute,
  AppPuslaRoute: AppPuslaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
