/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebSitesiRouteImport } from './routes/web-sitesi'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as OtomasyonRouteImport } from './routes/otomasyon'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as ButcelemeRouteImport } from './routes/butceleme'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppButcecrmRouteImport } from './routes/app.butcecrm'
import { Route as AppButcecrmIndexRouteImport } from './routes/app.butcecrm.index'
import { Route as AppButcecrmStokRouteImport } from './routes/app.butcecrm.stok'
import { Route as AppButcecrmSatislarRouteImport } from './routes/app.butcecrm.satislar'
import { Route as AppButcecrmReklamRouteImport } from './routes/app.butcecrm.reklam'
import { Route as AppButcecrmGiderlerRouteImport } from './routes/app.butcecrm.giderler'
import { Route as AppButcecrmCarilerRouteImport } from './routes/app.butcecrm.cariler'
import { Route as AppButcecrmAlislarRouteImport } from './routes/app.butcecrm.alislar'

const WebSitesiRoute = WebSitesiRouteImport.update({
  id: '/web-sitesi',
  path: '/web-sitesi',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomasyonRoute = OtomasyonRouteImport.update({
  id: '/otomasyon',
  path: '/otomasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const ButcelemeRoute = ButcelemeRouteImport.update({
  id: '/butceleme',
  path: '/butceleme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppButcecrmRoute = AppButcecrmRouteImport.update({
  id: '/app/butcecrm',
  path: '/app/butcecrm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppButcecrmIndexRoute = AppButcecrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmStokRoute = AppButcecrmStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmSatislarRoute = AppButcecrmSatislarRouteImport.update({
  id: '/satislar',
  path: '/satislar',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmReklamRoute = AppButcecrmReklamRouteImport.update({
  id: '/reklam',
  path: '/reklam',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmGiderlerRoute = AppButcecrmGiderlerRouteImport.update({
  id: '/giderler',
  path: '/giderler',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmCarilerRoute = AppButcecrmCarilerRouteImport.update({
  id: '/cariler',
  path: '/cariler',
  getParentRoute: () => AppButcecrmRoute,
} as any)
const AppButcecrmAlislarRoute = AppButcecrmAlislarRouteImport.update({
  id: '/alislar',
  path: '/alislar',
  getParentRoute: () => AppButcecrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butceleme': typeof ButcelemeRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/app/butcecrm': typeof AppButcecrmRouteWithChildren
  '/app/butcecrm/alislar': typeof AppButcecrmAlislarRoute
  '/app/butcecrm/cariler': typeof AppButcecrmCarilerRoute
  '/app/butcecrm/giderler': typeof AppButcecrmGiderlerRoute
  '/app/butcecrm/reklam': typeof AppButcecrmReklamRoute
  '/app/butcecrm/satislar': typeof AppButcecrmSatislarRoute
  '/app/butcecrm/stok': typeof AppButcecrmStokRoute
  '/app/butcecrm/': typeof AppButcecrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butceleme': typeof ButcelemeRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/app/butcecrm/alislar': typeof AppButcecrmAlislarRoute
  '/app/butcecrm/cariler': typeof AppButcecrmCarilerRoute
  '/app/butcecrm/giderler': typeof AppButcecrmGiderlerRoute
  '/app/butcecrm/reklam': typeof AppButcecrmReklamRoute
  '/app/butcecrm/satislar': typeof AppButcecrmSatislarRoute
  '/app/butcecrm/stok': typeof AppButcecrmStokRoute
  '/app/butcecrm': typeof AppButcecrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butceleme': typeof ButcelemeRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/otomasyon': typeof OtomasyonRoute
  '/panel': typeof PanelRoute
  '/web-sitesi': typeof WebSitesiRoute
  '/app/butcecrm': typeof AppButcecrmRouteWithChildren
  '/app/butcecrm/alislar': typeof AppButcecrmAlislarRoute
  '/app/butcecrm/cariler': typeof AppButcecrmCarilerRoute
  '/app/butcecrm/giderler': typeof AppButcecrmGiderlerRoute
  '/app/butcecrm/reklam': typeof AppButcecrmReklamRoute
  '/app/butcecrm/satislar': typeof AppButcecrmSatislarRoute
  '/app/butcecrm/stok': typeof AppButcecrmStokRoute
  '/app/butcecrm/': typeof AppButcecrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/butceleme'
    | '/hakkimizda'
    | '/iletisim'
    | '/otomasyon'
    | '/panel'
    | '/web-sitesi'
    | '/app/butcecrm'
    | '/app/butcecrm/alislar'
    | '/app/butcecrm/cariler'
    | '/app/butcecrm/giderler'
    | '/app/butcecrm/reklam'
    | '/app/butcecrm/satislar'
    | '/app/butcecrm/stok'
    | '/app/butcecrm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/butceleme'
    | '/hakkimizda'
    | '/iletisim'
    | '/otomasyon'
    | '/panel'
    | '/web-sitesi'
    | '/app/butcecrm/alislar'
    | '/app/butcecrm/cariler'
    | '/app/butcecrm/giderler'
    | '/app/butcecrm/reklam'
    | '/app/butcecrm/satislar'
    | '/app/butcecrm/stok'
    | '/app/butcecrm'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/butceleme'
    | '/hakkimizda'
    | '/iletisim'
    | '/otomasyon'
    | '/panel'
    | '/web-sitesi'
    | '/app/butcecrm'
    | '/app/butcecrm/alislar'
    | '/app/butcecrm/cariler'
    | '/app/butcecrm/giderler'
    | '/app/butcecrm/reklam'
    | '/app/butcecrm/satislar'
    | '/app/butcecrm/stok'
    | '/app/butcecrm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ButcelemeRoute: typeof ButcelemeRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  OtomasyonRoute: typeof OtomasyonRoute
  PanelRoute: typeof PanelRoute
  WebSitesiRoute: typeof WebSitesiRoute
  AppButcecrmRoute: typeof AppButcecrmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-sitesi': {
      id: '/web-sitesi'
      path: '/web-sitesi'
      fullPath: '/web-sitesi'
      preLoaderRoute: typeof WebSitesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomasyon': {
      id: '/otomasyon'
      path: '/otomasyon'
      fullPath: '/otomasyon'
      preLoaderRoute: typeof OtomasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/butceleme': {
      id: '/butceleme'
      path: '/butceleme'
      fullPath: '/butceleme'
      preLoaderRoute: typeof ButcelemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/butcecrm': {
      id: '/app/butcecrm'
      path: '/app/butcecrm'
      fullPath: '/app/butcecrm'
      preLoaderRoute: typeof AppButcecrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/butcecrm/': {
      id: '/app/butcecrm/'
      path: '/'
      fullPath: '/app/butcecrm/'
      preLoaderRoute: typeof AppButcecrmIndexRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/stok': {
      id: '/app/butcecrm/stok'
      path: '/stok'
      fullPath: '/app/butcecrm/stok'
      preLoaderRoute: typeof AppButcecrmStokRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/satislar': {
      id: '/app/butcecrm/satislar'
      path: '/satislar'
      fullPath: '/app/butcecrm/satislar'
      preLoaderRoute: typeof AppButcecrmSatislarRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/reklam': {
      id: '/app/butcecrm/reklam'
      path: '/reklam'
      fullPath: '/app/butcecrm/reklam'
      preLoaderRoute: typeof AppButcecrmReklamRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/giderler': {
      id: '/app/butcecrm/giderler'
      path: '/giderler'
      fullPath: '/app/butcecrm/giderler'
      preLoaderRoute: typeof AppButcecrmGiderlerRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/cariler': {
      id: '/app/butcecrm/cariler'
      path: '/cariler'
      fullPath: '/app/butcecrm/cariler'
      preLoaderRoute: typeof AppButcecrmCarilerRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
    '/app/butcecrm/alislar': {
      id: '/app/butcecrm/alislar'
      path: '/alislar'
      fullPath: '/app/butcecrm/alislar'
      preLoaderRoute: typeof AppButcecrmAlislarRouteImport
      parentRoute: typeof AppButcecrmRoute
    }
  }
}

interface AppButcecrmRouteChildren {
  AppButcecrmAlislarRoute: typeof AppButcecrmAlislarRoute
  AppButcecrmCarilerRoute: typeof AppButcecrmCarilerRoute
  AppButcecrmGiderlerRoute: typeof AppButcecrmGiderlerRoute
  AppButcecrmReklamRoute: typeof AppButcecrmReklamRoute
  AppButcecrmSatislarRoute: typeof AppButcecrmSatislarRoute
  AppButcecrmStokRoute: typeof AppButcecrmStokRoute
  AppButcecrmIndexRoute: typeof AppButcecrmIndexRoute
}

const AppButcecrmRouteChildren: AppButcecrmRouteChildren = {
  AppButcecrmAlislarRoute: AppButcecrmAlislarRoute,
  AppButcecrmCarilerRoute: AppButcecrmCarilerRoute,
  AppButcecrmGiderlerRoute: AppButcecrmGiderlerRoute,
  AppButcecrmReklamRoute: AppButcecrmReklamRoute,
  AppButcecrmSatislarRoute: AppButcecrmSatislarRoute,
  AppButcecrmStokRoute: AppButcecrmStokRoute,
  AppButcecrmIndexRoute: AppButcecrmIndexRoute,
}

const AppButcecrmRouteWithChildren = AppButcecrmRoute._addFileChildren(
  AppButcecrmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ButcelemeRoute: ButcelemeRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  OtomasyonRoute: OtomasyonRoute,
  PanelRoute: PanelRoute,
  WebSitesiRoute: WebSitesiRoute,
  AppButcecrmRoute: AppButcecrmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
